In [1]:
!pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.0-py3-none-any.whl (1.4 MB)
                                              0.0/1.4 MB ? eta -:--:--
     ------                                   0.2/1.4 MB 6.9 MB/s eta 0:00:01
     ------                                   0.2/1.4 MB 6.9 MB/s eta 0:00:01
     -------------------                      0.7/1.4 MB 5.5 MB/s eta 0:00:01
     ---------------------------              1.0/1.4 MB 5.7 MB/s eta 0:00:01
     ------------------------------------     1.3/1.4 MB 6.1 MB/s eta 0:00:01
     ---------------------------------------- 1.4/1.4 MB 5.8 MB/s eta 0:00:00
Requirement already satisfied: scipy>=1.2.1 in c:\users\sanik\anaconda3\lib\site-packages (from mlxtend) (1.10.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\sanik\anaconda3\lib\site-packages (from mlxtend) (1.24.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\sanik\anaconda3\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\sanik\anaconda3\lib\site-packages (from mlxtend) (1.2.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\sanik\anaconda3\lib\site-packages (from mlxtend) (3.7.1)
Requirement already satisfied: joblib>=0.13.2 in c:\users\sanik\anaconda3\lib\site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sanik\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\sanik\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sanik\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\sanik\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\sanik\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\sanik\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sanik\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sanik\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sanik\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2022.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sanik\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\sanik\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.0

In [2]:
import csv

In [3]:
dataset=[]
with open('Order2.csv') as file:
    reader=csv.reader(file,delimiter=',')
    for row in reader:
        dataset+=[row]

In [4]:
dataset[0:10]

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries']]

In [5]:
from mlxtend.preprocessing import TransactionEncoder

In [6]:
#convert data to transaction encoder
te=TransactionEncoder()
x=te.fit_transform(dataset)
x

array([[False,  True,  True, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]])

In [7]:
#bulid model

In [8]:
from mlxtend.frequent_patterns import apriori,association_rules

In [11]:
dataset[0:10]

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries']]

In [12]:
import pandas as pd

In [15]:
df=pd.DataFrame(x,columns=te.columns_)

In [16]:
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [25]:
freq_itemset=apriori(df,min_support=0.01,use_colnames=True)

In [26]:
freq_itemset

      support                                 itemsets
0    0.020397                                (almonds)
1    0.033329                                (avocado)
2    0.010799                         (barbecue sauce)
3    0.014265                              (black tea)
4    0.011465                             (body spray)
..        ...                                      ...
252  0.011065       (mineral water, ground beef, milk)
253  0.017064  (spaghetti, mineral water, ground beef)
254  0.015731         (spaghetti, mineral water, milk)
255  0.010265    (olive oil, spaghetti, mineral water)
256  0.011465     (spaghetti, mineral water, pancakes)

[257 rows x 2 columns]

In [28]:
rules=association_rules(freq_itemset,metrix='confidance',min_threshold=0.25)

TypeError: association_rules() got an unexpected keyword argument 'metrix'

In [29]:
rules=association_rules(freq_itemset,metric='confidance',min_threshold=0.25)

ValueError: Metric must be 'confidence' or 'lift', got 'confidance'

In [31]:
rules=association_rules(freq_itemset,metric='confidence',min_threshold=0.25)

In [32]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(avocado),(mineral water),0.033329,0.238368,0.011598,0.348000,1.459926,0.003654,1.168147,0.325896
1,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,0.013128,1.224818,0.499424
2,(burgers),(french fries),0.087188,0.170911,0.021997,0.252294,1.476173,0.007096,1.108844,0.353384
3,(burgers),(mineral water),0.087188,0.238368,0.024397,0.279817,1.173883,0.003614,1.057552,0.162275
4,(cake),(mineral water),0.081056,0.238368,0.027463,0.338816,1.421397,0.008142,1.151921,0.322617
...,...,...,...,...,...,...,...,...,...,...
90,"(mineral water, milk)",(spaghetti),0.047994,0.174110,0.015731,0.327778,1.882589,0.007375,1.228597,0.492451
91,"(spaghetti, olive oil)",(mineral water),0.022930,0.238368,0.010265,0.447674,1.878079,0.004799,1.378954,0.478514
92,"(mineral water, olive oil)",(spaghetti),0.027596,0.174110,0.010265,0.371981,2.136468,0.005460,1.315071,0.547034
93,"(spaghetti, pancakes)",(mineral water),0.025197,0.238368,0.011465,0.455026,1.908923,0.005459,1.397557,0.488452
94,"(mineral water, pancakes)",(spaghetti),0.033729,0.174110,0.011465,0.339921,1.952333,0.005593,1.251198,0.504819

In [33]:
rules=rules[['antecedents','consequents','support','confidence']]

In [34]:
rules

                   antecedents      consequents   support  confidence
0                    (avocado)  (mineral water)  0.011598    0.348000
1                    (burgers)           (eggs)  0.028796    0.330275
2                    (burgers)   (french fries)  0.021997    0.252294
3                    (burgers)  (mineral water)  0.024397    0.279817
4                       (cake)  (mineral water)  0.027463    0.338816
..                         ...              ...       ...         ...
90       (mineral water, milk)      (spaghetti)  0.015731    0.327778
91      (spaghetti, olive oil)  (mineral water)  0.010265    0.447674
92  (mineral water, olive oil)      (spaghetti)  0.010265    0.371981
93       (spaghetti, pancakes)  (mineral water)  0.011465    0.455026
94   (mineral water, pancakes)      (spaghetti)  0.011465    0.339921

[95 rows x 4 columns]

In [36]:
rules[rules['antecedents']=={'cake'}]['consequents']

4    (mineral water)
Name: consequents, dtype: object